on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    continue-on-error: ${{ matrix.os == 'windows-latest' }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: master
      - run: zig build test examples run install
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.1"
      - run: ./examples/test_terminfo.py -v

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: master
      - run: zig fmt --check .
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.1"
      - run: uvx ruff format --check .
