on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: 0.14.1
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.1"
      - run: make tests
      - run: CC='zig cc' make c

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: 0.14.1
      - run: zig fmt --check .
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.1"
      - run: uvx ruff format --check .
